CREATE TABLE USER (
USER_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
FIRSTNAME VARCHAR(50) NOT NULL,
LASTNAME VARCHAR(50) NOT NULL,
EMPLOYEE_ID VARCHAR(10) NOT NULL);

CREATE TABLE PROJECT (
PROJECT_ID INT(6) UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
PROJECT VARCHAR(50) NOT NULL,
STARTDATE DATE,
ENDDATE DATE,
PRIORITY INT(3),
USER_ID INTEGER UNSIGNED NOT NULL,
CONSTRAINT FK_MANAGER_ID FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID));

CREATE TABLE PARENTTASK(
PARENT_ID INT(6) UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
PARENT_TASK VARCHAR(50) NOT NULL);

CREATE TABLE TASK(
TASK_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
PARENT_ID INT(6) UNSIGNED NOT NULL,
PROJECT_ID INT(6) UNSIGNED NOT NULL,
USER_ID INTEGER UNSIGNED NOT NULL,
TASK VARCHAR(50) NOT NULL,
STARTDATE DATE,
ENDDATE DATE,
PRIORITY INT(3),
STATUS VARCHAR(3) NOT NULL,
CONSTRAINT FK_PARENT_ID FOREIGN KEY (PARENT_ID) REFERENCES PARENTTASK(PARENT_ID),
CONSTRAINT FK_PROJECT_ID FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(PROJECT_ID),
CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID));